apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-devops-eks
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: aws-devops-eks
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-devops-eks
    spec:
      containers:
      - name: aws-devops-eks
        image: ghcr.io/ifaridi79/aws-devops-eks:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m