name: CI Pipeline


on:
  pull_request:
    branches: [ "main" ]


env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    TAG: ${{ vars.VERSION }}
    VERSION: PR_${{ github.event.pull_request.number }}
  
permissions:
   contents: read
  
jobs:
    build_code:
      name: 'Code Build'
      runs-on: ubuntu-latest
  
      steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
  
      # Set Pyhton environment
      - name: Set up Node 15
        uses: actions/setup-node@v3
        with:
            node-version: '15'        
      
      # Install all the dependencies
      - name: Install dependencies
        run: npm --prefix codebase/rdicidr-0.1.0 install
  
      # Lint code
      - name: Lint Code
        run: npm --prefix codebase/rdicidr-0.1.0 run lint
  
      # Code Format using Prettier        
      - name: Code Format (Prettier)
        run: npm --prefix codebase/rdicidr-0.1.0 run prettier

      # Unit Test        
      - name: Unit Testing (Jest)
        run: CI=true npm --prefix codebase/rdicidr-0.1.0 test        

      # Production build distribution folder       
      - name: Build the code
        run: npm --prefix codebase/rdicidr-0.1.0 run build           
  
    build-and-push-image:
      needs: [build_code]
      name: 'Build and Push Docker Image'    
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
  
      steps:
      # Checking out the code
      - name: Checkout repository
        uses: actions/checkout@v3
  
      # Login into Container GitHub Registry Package Manager  
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      # Building the Docker image and tag    
      - name: Build and tag image
        run: docker build -f codebase/Dockerfile -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}" -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}" .
  
      # Push to GitHub Registry  
      - name: Push to GitHub Registry
        run: docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}   
